=== arkoebel/osiris/xsd/SCTCvfBlkCredTrf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- STEP2 SCT Schema, SCTCvfBlkCredTrf, Jul 15th 2013, Release February 2014 -->
<!-- STEP2 Renamed pacs.002.001.03S2 to FIToFIPmtStsRptS2, March 29th 2010 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sw5="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03S2" xmlns:S2SCTCvf="urn:S2SCTCvf:xsd:$SCTCvfBlkCredTrf" xmlns:ns1="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03S2" targetNamespace="urn:S2SCTCvf:xsd:$SCTCvfBlkCredTrf" elementFormDefault="qualified">
	<xs:import namespace="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03S2" schemaLocation="pacs.002.001.03S2.xsd"/>
	<xs:element name="SCTCvfBlkCredTrf">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SndgInst" type="sw5:BICIdentifier"/>
				<xs:element name="RcvgInst" type="sw5:BICIdentifier"/>
				<xs:element name="SrvcId" type="S2SCTCvf:SrvcID"/>
				<xs:element name="TstCode" type="S2SCTCvf:TestCodeType"/>
				<xs:element name="FType" type="S2SCTCvf:FTpType"/>
				<xs:element name="FileRef" type="sw5:Max16Text"/>
				<xs:element name="FileDtTm" type="sw5:ISODateTime"/>
				<xs:element name="OrigFRef" type="sw5:Max16Text" minOccurs="0"/>
				<xs:element name="OrigFName" type="S2SCTCvf:Max32Text"/>
				<xs:element name="OrigDtTm" type="sw5:ISODateTime" minOccurs="0"/>
				<xs:element name="FileRjctRsn" type="S2SCTCvf:Text3"/>
				<xs:element name="FileBusDt" type="sw5:ISODate"/>
				<xs:element name="FileCycleNo" type="S2SCTCvf:Max2NumericText"/>
				<xs:element name="FIToFIPmtStsRptS2" type="sw5:FIToFIPaymentStatusReportV03" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="Max32Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Text3">
		<xs:restriction base="xs:string">
			<xs:length value="3" fixed="true"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FTpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CVF"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TestCodeType">
		<xs:restriction base="xs:string">
			<xs:length value="1"/>
			<xs:enumeration value="T"/>
			<xs:enumeration value="P"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SrvcID">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SCT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max2NumericText">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{2,2}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== arkoebel/osiris/templates/errheader.xml
<S2SCTCvf:SCTCvfBlkCredTrf xmlns:S2SCTCvf="urn:S2SCTCvf:xsd:$SCTCvfBlkCredTrf" xmlns:p="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.02S2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:S2SCTCvf:xsd:$SCTCvfBlkCredTrf SCTCvfBlkCredTrf.xsd urn:iso:std:iso:20022:tech:xsd:pacs.002.001.02S2 pacs.002.001.02S2.xsd ">
  <S2SCTCvf:SndgInst><?= $sender ?></S2SCTCvf:SndgInst>
  <S2SCTCvf:RcvgInst><?= $receiver ?></S2SCTCvf:RcvgInst>
  <S2SCTCvf:SrvcId><?= 'SCT' ?></S2SCTCvf:SrvcId>
  <S2SCTCvf:TstCode>T</S2SCTCvf:TstCode>
  <S2SCTCvf:FType><?= 'CVF' ?></S2SCTCvf:FType>
  <S2SCTCvf:FileRef><?= $outref ?></S2SCTCvf:FileRef>
  <S2SCTCvf:FileDtTm><?= gmdate('Y-m-d\TH:i:s\Z') ?></S2SCTCvf:FileDtTm>
  <S2SCTCvf:OrigFName><?= $source ?></S2SCTCvf:OrigFName>
  <S2SCTCvf:FileRjctRsn><?= $error ?></S2SCTCvf:FileRjctRsn>
  <S2SCTCvf:FileBusDt><?= gmdate('Y-m-d') ?></S2SCTCvf:FileBusDt>
  <S2SCTCvf:FileCycleNo>01</S2SCTCvf:FileCycleNo>
</S2SCTCvf:SCTCvfBlkCredTrf>

=== arkoebel/osiris/templates/outheader.xml
<S2SCTCvf:SCTCvfBlkCredTrf xmlns:S2SCTCvf="urn:S2SCTCvf:xsd:$SCTCvfBlkCredTrf" xmlns:p="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.02S2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:S2SCTCvf:xsd:$SCTCvfBlkCredTrf SCTCvfBlkCredTrf.xsd urn:iso:std:iso:20022:tech:xsd:pacs.002.001.02S2 pacs.002.001.02S2.xsd ">
  <S2SCTCvf:SndgInst><?= $params['receiver'] ?></S2SCTCvf:SndgInst>
  <S2SCTCvf:RcvgInst><?= $params['sender'] ?></S2SCTCvf:RcvgInst>
  <S2SCTCvf:SrvcId><?= 'SCT' ?></S2SCTCvf:SrvcId>
  <S2SCTCvf:TstCode>T</S2SCTCvf:TstCode>
  <S2SCTCvf:FType><?= 'CVF' ?></S2SCTCvf:FType>
  <S2SCTCvf:FileRef><?= $outref ?></S2SCTCvf:FileRef>
  <S2SCTCvf:FileDtTm><?= gmdate('Y-m-d\TH:i:s\Z') ?></S2SCTCvf:FileDtTm>
  <S2SCTCvf:OrigFRef><?= $params['ref'] ?></S2SCTCvf:OrigFRef>
  <S2SCTCvf:OrigFName><?= $file ?></S2SCTCvf:OrigFName>
  <S2SCTCvf:OrigDtTm><?= $params['filedate'] ?></S2SCTCvf:OrigDtTm>
  <S2SCTCvf:FileRjctRsn><?= $params['error'] ?></S2SCTCvf:FileRjctRsn>
  <S2SCTCvf:FileBusDt><?= gmdate('Y-m-d') ?></S2SCTCvf:FileBusDt>
  <S2SCTCvf:FileCycleNo>01</S2SCTCvf:FileCycleNo>
</S2SCTCvf:SCTCvfBlkCredTrf>
